name: Validate

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - release/*
    paths-ignore:
      - docs/*
      - "*.md"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
